# TWILIO_SID: "AC8ccce571737489fc17bf8b770a8633c9"
# TWILIO_TOKEN: "ce71e5caf5ad0650f339aed13b44cec5"
# TWILIO_PHONE_NUMBER: "+19183763752"
gmail_username: 'signup.onejobstreet@gmail.com'
gmail_password: 'tadbuch6'
